CREATE TABLE `contactLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`contactId` int,
	`logDate` date NOT NULL,
	`contactMethod` varchar(64),
	`teamMember` int,
	`interactionSummary` text,
	`responseResult` varchar(160),
	`followupRequired` boolean NOT NULL DEFAULT false,
	`nextFollowupDate` date,
	`followupAction` text,
	`followupCompleted` boolean NOT NULL DEFAULT false,
	`attachmentUrl` varchar(512),
	`loggedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contactLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`contactName` varchar(160) NOT NULL,
	`roleDepartment` varchar(120),
	`email` varchar(320),
	`phone` varchar(40),
	`linkedinUrl` varchar(255),
	`preferredContactMethod` varchar(64),
	`referralSource` varchar(160),
	`isDecisionMaker` boolean NOT NULL DEFAULT false,
	`contactStatus` varchar(64),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `offersAgreements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sponsorId` int NOT NULL,
	`eventInitiative` varchar(160),
	`offerType` varchar(64),
	`offerDescription` text,
	`cashValue` decimal(12,2) DEFAULT '0',
	`inKindValue` decimal(12,2) DEFAULT '0',
	`offerDate` date,
	`decisionStatus` varchar(64),
	`agreementStatus` varchar(64),
	`agreementLink` varchar(512),
	`invoiceNumber` varchar(80),
	`invoiceDate` date,
	`paymentStatus` varchar(64),
	`amountReceived` decimal(12,2) DEFAULT '0',
	`paymentDate` date,
	`deliverablesPromised` text,
	`clubDeliverables` text,
	`activationDeadline` date,
	`ownerId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `offersAgreements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sponsors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`displayId` varchar(32) NOT NULL,
	`companyName` varchar(160) NOT NULL,
	`website` varchar(255),
	`sponsorType` varchar(64),
	`industry` varchar(96),
	`cityRegion` varchar(120),
	`primaryEvent` varchar(160),
	`potentialFit` text,
	`priority` enum('High','Medium','Low') NOT NULL DEFAULT 'Medium',
	`pipelineStatus` enum('Lead','Contacted','Meeting','Proposal','Confirmed','Not a fit') NOT NULL DEFAULT 'Lead',
	`ownerId` int,
	`lastContactDate` date,
	`nextFollowupDate` date,
	`bestContactMethod` varchar(64),
	`estimatedValue` decimal(12,2) DEFAULT '0',
	`currency` varchar(8) NOT NULL DEFAULT 'INR',
	`likelySupportType` varchar(64),
	`proposalSent` boolean NOT NULL DEFAULT false,
	`meetingDate` date,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sponsors_id` PRIMARY KEY(`id`),
	CONSTRAINT `sponsors_displayId_unique` UNIQUE(`displayId`)
);
